import json
import re

# Read the JSON file
with open(str(Path(__file__).parent.parent / "cism_questions.json"), 'r', encoding='utf-8') as f:
    data = json.load(f)

# Dictionary of common spaced word patterns to fix
# Based on common OCR/formatting errors
spaced_word_fixes = {
    r'\blar ge\b': 'large',
    r'\bef fective\b': 'effective',
    r'\bef fectively\b': 'effectively',
    r'\bemer gency\b': 'emergency',
    r'\bor ganization\b': 'organization',
    r'\bor ganizations\b': 'organizations',
    r'\bor ganizational\b': 'organizational',
    r'\bof ficer\b': 'officer',
    r'\bof ficers\b': 'officers',
    r'\bdif ferent\b': 'different',
    r'\bdif ference\b': 'difference',
    r'\bper formance\b': 'performance',
    r'\bper form\b': 'perform',
    r'\bper forming\b': 'performing',
    r'\bper formed\b': 'performed',
    r'\bde partment\b': 'department',
    r'\bde partments\b': 'departments',
    r'\ben gine\b': 'engine',
    r'\ben gineering\b': 'engineering',
    r'\bman agement\b': 'management',
    r'\bman aged\b': 'managed',
    r'\bman age\b': 'manage',
    r'\bman ager\b': 'manager',
    r'\bman agers\b': 'managers',
    r'\bin cident\b': 'incident',
    r'\bin cidents\b': 'incidents',
    r'\bin formation\b': 'information',
    r'\bin fringe\b': 'infringe',
    r'\bun derstand\b': 'understand',
    r'\bun derstands\b': 'understands',
    r'\bun derstood\b': 'understood',
    r'\bun derstanding\b': 'understanding',
    r'\bse curity\b': 'security',
    r'\bse cure\b': 'secure',
    r'\bse cured\b': 'secured',
    r'\bse curing\b': 'securing',
    r'\bre sponsibility\b': 'responsibility',
    r'\bre sponsible\b': 'responsible',
    r'\bst akeholder\b': 'stakeholder',
    r'\bst akeholders\b': 'stakeholders',
    r'\bbu siness\b': 'business',
    r'\bbu siness\b': 'business',
    r'\bac tivity\b': 'activity',
    r'\bac tivities\b': 'activities',
    r'\bpe rsonnel\b': 'personnel',
    r'\bpe rsonal\b': 'personal',
    r'\bpe rson\b': 'person',
    r'\bpr ocess\b': 'process',
    r'\bpr ocesses\b': 'processes',
    r'\bpr ocessing\b': 'processing',
    r'\bpr ocessed\b': 'processed',
    r'\bco mpany\b': 'company',
    r'\bco mpanies\b': 'companies',
    r'\bco mpare\b': 'compare',
    r'\bco mpared\b': 'compared',
    r'\bco mparison\b': 'comparison',
    r'\bas sessment\b': 'assessment',
    r'\bas sess\b': 'assess',
    r'\bas sessed\b': 'assessed',
    r'\bfi nance\b': 'finance',
    r'\bfi nancial\b': 'financial',
    r'\bop eration\b': 'operation',
    r'\bop erations\b': 'operations',
    r'\bop erational\b': 'operational',
    r'\bop erator\b': 'operator',
    r'\bop erators\b': 'operators',
    r'\ben vironment\b': 'environment',
    r'\ben vironmental\b': 'environmental',
    r'\bqu ality\b': 'quality',
    r'\bqu alified\b': 'qualified',
    r'\bqu alify\b': 'qualify',
    r'\bva lue\b': 'value',
    r'\bva lues\b': 'values',
    r'\bva lued\b': 'valued',
    r'\bpr ivate\b': 'private',
    r'\bpr ivacy\b': 'privacy',
    r'\bpu blic\b': 'public',
    r'\bpu blicly\b': 'publicly',
    r'\bpo licy\b': 'policy',
    r'\bpo licies\b': 'policies',
    r'\bpr otect\b': 'protect',
    r'\bpr otection\b': 'protection',
    r'\bpr otected\b': 'protected',
    r'\bpr otecting\b': 'protecting',
    r'\bdr ive\b': 'drive',
    r'\bdr ives\b': 'drives',
    r'\bdr iver\b': 'driver',
    r'\bco ntrol\b': 'control',
    r'\bco ntrols\b': 'controls',
    r'\bco ntrolled\b': 'controlled',
    r'\bco ntrolling\b': 'controlling',
    r'\bde cision\b': 'decision',
    r'\bde cisions\b': 'decisions',
    r'\bde cide\b': 'decide',
    r'\bde cides\b': 'decides',
    r'\bde cided\b': 'decided',
    r'\bde ciding\b': 'deciding',
    r'\bse rvice\b': 'service',
    r'\bse rvices\b': 'services',
    r'\bse rve\b': 'serve',
    r'\bse rves\b': 'serves',
    r'\bse rved\b': 'served',
    r'\bse rving\b': 'serving',
    r'\bsu pport\b': 'support',
    r'\bsu pports\b': 'supports',
    r'\bsu pported\b': 'supported',
    r'\bsu pporting\b': 'supporting',
    r'\bpr ovide\b': 'provide',
    r'\bpr ovides\b': 'provides',
    r'\bpr ovided\b': 'provided',
    r'\bpr oviding\b': 'providing',
    r'\bpr ovision\b': 'provision',
    r'\bpr ovisions\b': 'provisions',
    r'\bad dress\b': 'address',
    r'\bad dresses\b': 'addresses',
    r'\bad dressed\b': 'addressed',
    r'\bad dressing\b': 'addressing',
    r'\bap ply\b': 'apply',
    r'\bap plies\b': 'applies',
    r'\bap plied\b': 'applied',
    r'\bap plicable\b': 'applicable',
    r'\bap plication\b': 'application',
    r'\bap plications\b': 'applications',
    r'\bch ange\b': 'change',
    r'\bch anges\b': 'changes',
    r'\bch anged\b': 'changed',
    r'\bch anging\b': 'changing',
    r'\bde velop\b': 'develop',
    r'\bde velops\b': 'develops',
    r'\bde veloped\b': 'developed',
    r'\bde veloping\b': 'developing',
    r'\bde velopment\b': 'development',
    r'\bme aning\b': 'meaning',
    r'\bme aningful\b': 'meaningful',
    r'\bsi gnificant\b': 'significant',
    r'\bsi gnificance\b': 'significance',
    r'\bsi gnificantly\b': 'significantly',
    r'\bco mpliance\b': 'compliance',
    r'\bco mpliant\b': 'compliant',
    r'\bco mply\b': 'comply',
    r'\bco mplies\b': 'complies',
    r'\bco mplied\b': 'complied',
    r'\bco mplying\b': 'complying',
    r'\bef fort\b': 'effort',
    r'\bef forts\b': 'efforts',
    r'\bap proach\b': 'approach',
    r'\bap proaches\b': 'approaches',
    r'\bap proached\b': 'approached',
    r'\bap proaching\b': 'approaching',
    r'\bfe bruary\b': 'february',
    r'\bfe ature\b': 'feature',
    r'\bfe atures\b': 'features',
    r'\bfe atured\b': 'featured',
    r'\bco mmunication\b': 'communication',
    r'\bco mmunications\b': 'communications',
    r'\bco mmunicate\b': 'communicate',
    r'\bco mmunicated\b': 'communicated',
    r'\bco mmon\b': 'common',
    r'\bco mmonly\b': 'commonly',
    r'\bco mmittee\b': 'committee',
    r'\bco mmittees\b': 'committees',
    r'\bsi tuation\b': 'situation',
    r'\bsi tuations\b': 'situations',
    r'\bri sk\b': 'risk',
    r'\bri sks\b': 'risks',
    r'\bri sked\b': 'risked',
    r'\bri sking\b': 'risking',
    r'\bst atement\b': 'statement',
    r'\bst atements\b': 'statements',
    r'\bst ate\b': 'state',
    r'\bst ates\b': 'states',
    r'\bst ated\b': 'stated',
    r'\bst ating\b': 'stating',
    r'\bdo cument\b': 'document',
    r'\bdo cuments\b': 'documents',
    r'\bdo cumented\b': 'documented',
    r'\bdo cumenting\b': 'documenting',
    r'\bma jor\b': 'major',
    r'\bmi nor\b': 'minor',
    r'\ble vel\b': 'level',
    r'\ble vels\b': 'levels',
    r'\bev aluation\b': 'evaluation',
    r'\bev aluations\b': 'evaluations',
    r'\bev aluate\b': 'evaluate',
    r'\bev aluated\b': 'evaluated',
    r'\bev aluating\b': 'evaluating',
    r'\bex ample\b': 'example',
    r'\bex amples\b': 'examples',
    r'\bex amine\b': 'examine',
    r'\bex amined\b': 'examined',
    r'\bex amining\b': 'examining',
}

# Apply fixes
fixed_count = 0
for question in data:
    for field in ['question', 'explanation']:
        if field in question and question[field]:
            original = question[field]
            for pattern, replacement in spaced_word_fixes.items():
                question[field], count = re.subn(pattern, replacement, question[field], flags=re.IGNORECASE)
                fixed_count += count
    
    for choice_key in ['A', 'B', 'C', 'D']:
        if choice_key in question['choices'] and question['choices'][choice_key]:
            original = question['choices'][choice_key]
            for pattern, replacement in spaced_word_fixes.items():
                question['choices'][choice_key], count = re.subn(pattern, replacement, question['choices'][choice_key], flags=re.IGNORECASE)
                fixed_count += count

# Save the fixed JSON
with open(str(Path(__file__).parent.parent / "cism_questions.json"), 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"✓ Fixed {fixed_count} spaced words")
print(f"✓ Successfully saved to cism_questions.json")

